// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team8.Data;

namespace Team8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190424102301_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Team8.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Team8.Models.Degree", b =>
                {
                    b.Property<int>("DegreeId");

                    b.Property<string>("DegreeAbbrev")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("DegreeId");

                    b.ToTable("Degree");
                });

            modelBuilder.Entity("Team8.Models.DegreeRequirement", b =>
                {
                    b.Property<int>("DegreeRequirementId");

                    b.Property<int>("DegreeId");

                    b.Property<string>("RequirementAbbrev")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("RequirementName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<int>("RequirementNumber");

                    b.HasKey("DegreeRequirementId");

                    b.HasIndex("DegreeId");

                    b.ToTable("DegreeRequirement");
                });

            modelBuilder.Entity("Team8.Models.DegreeStatus", b =>
                {
                    b.Property<int>("DegreeStatusId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("DegreeStatusId");

                    b.ToTable("DegreeStatus");
                });

            modelBuilder.Entity("Team8.Models.PlanTerm", b =>
                {
                    b.Property<int>("PlanTermId");

                    b.Property<int>("StudentDegreePlanId");

                    b.Property<string>("TermAbbrev")
                        .HasMaxLength(20);

                    b.Property<int>("TermNumber");

                    b.HasKey("PlanTermId");

                    b.HasIndex("StudentDegreePlanId");

                    b.ToTable("PlanTerm");
                });

            modelBuilder.Entity("Team8.Models.PlanTermRequirement", b =>
                {
                    b.Property<int>("PlanTermRequirementId");

                    b.Property<int>("DegreeRequirementId");

                    b.Property<int>("PlanTermId");

                    b.Property<int>("RequirementStatusId");

                    b.HasKey("PlanTermRequirementId");

                    b.HasIndex("DegreeRequirementId");

                    b.HasIndex("PlanTermId");

                    b.HasIndex("RequirementStatusId");

                    b.ToTable("PlanTermRequirement");
                });

            modelBuilder.Entity("Team8.Models.RequirementStatus", b =>
                {
                    b.Property<int>("RequirementStatusId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("RequirementStatusId");

                    b.ToTable("RequirementStatus");
                });

            modelBuilder.Entity("Team8.Models.Student", b =>
                {
                    b.Property<int>("StudentId");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(50);

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("StudentId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Team8.Models.StudentDegreePlan", b =>
                {
                    b.Property<int>("StudentDegreePlanId");

                    b.Property<int>("DegreeId");

                    b.Property<int>("DegreeStatusId");

                    b.Property<bool>("IncludesInternship");

                    b.Property<string>("PlanAbbrev")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("PlanNumber");

                    b.Property<int>("StudentId");

                    b.HasKey("StudentDegreePlanId");

                    b.HasIndex("DegreeId");

                    b.HasIndex("DegreeStatusId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentDegreePlan");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Team8.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Team8.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Team8.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Team8.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team8.Models.DegreeRequirement", b =>
                {
                    b.HasOne("Team8.Models.Degree", "Degree")
                        .WithMany("DegreeRequirements")
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team8.Models.PlanTerm", b =>
                {
                    b.HasOne("Team8.Models.StudentDegreePlan", "StudentDegreePlan")
                        .WithMany("PlanTerms")
                        .HasForeignKey("StudentDegreePlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team8.Models.PlanTermRequirement", b =>
                {
                    b.HasOne("Team8.Models.DegreeRequirement", "DegreeRequirement")
                        .WithMany()
                        .HasForeignKey("DegreeRequirementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Team8.Models.PlanTerm", "PlanTerm")
                        .WithMany("PlanTermRequirements")
                        .HasForeignKey("PlanTermId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Team8.Models.RequirementStatus", "RequirementStatus")
                        .WithMany()
                        .HasForeignKey("RequirementStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Team8.Models.StudentDegreePlan", b =>
                {
                    b.HasOne("Team8.Models.Degree", "Degree")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Team8.Models.DegreeStatus", "DegreeStatus")
                        .WithMany()
                        .HasForeignKey("DegreeStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Team8.Models.Student", "Student")
                        .WithMany("StudentDegreePlans")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
